// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package tutorial

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64
	Owner     sql.NullString
	Balance   sql.NullInt64
	Currency  sql.NullString
	CreatedAt time.Time
}

type Entry struct {
	ID        sql.NullInt64
	AccountID sql.NullInt64
	Amount    sql.NullInt64
	CreatedAt time.Time
}

type Transfer struct {
	ID            sql.NullInt64
	FromAccountID sql.NullInt64
	ToAccountID   sql.NullInt64
	Amount        sql.NullInt64
	CreatedAt     time.Time
}
